const coursesDataValues = [
  {id: 1, courseName: "Front-End Development", color: "orange", textcl: "#fff"},
  {id: 2, courseName: "Backend Programming", color: "blue", textcl: "#fff"},
  {id: 3, courseName: "Power BI", color: "gold", textcl: "#fff"},
  {id: 4, courseName: "Content Creation & Social Media Marketing", color: "green", textcl: "#fff"},
  {id: 5, courseName: "Data Entry", color: "black", textcl: "#fff"},
  {id: 6, courseName: "Virtual Assistant", color: "#1a73e8", textcl: "#fff",},
  {id: 7, courseName: "Basic Computing", color: "blue", textcl: "#fff"},
  {id: 8, courseName: "Copy Writing", color: "green", textcl: "#fff"},
  {id: 9, courseName: "Mobile App Development", color: "blue", textcl: "#fff"},
  {id: 10, courseName: "Generative AI", color: "red", textcl: "#fff"},
  {id: 11, courseName: "Project Management", color: "violet", textcl: "#fff"},
  {id: 12, courseName: "Graphics Design", color: "green", textcl: "#fff"},
  {id: 13, courseName: "UI/UX Design", color: "orange", textcl: "#fff"},
  {id: 14, courseName: "Full Stack Development", color: "red", textcl: "#fff"},
  {id: 15, courseName: "Cyber Security", color: "blue", textcl: "#fff"},
  {id: 16, courseName: "Data Analytics", color: "gold", textcl: "#fff"},
  {id: 17, courseName: "SQL Database", color: "blue", textcl: "#fff"},
  {id: 18, courseName: "Python for Data Analysis", color: "gold", textcl: "#fff"},
  {id: 19, courseName: "Excel for Data Analysis", color: "green", textcl: "#fff"},
  {id: 20, courseName: "Digital Marketing", color: "red", textcl: "#fff"},
];